/*
 * Copyright (c) 2025 VK DIGITAL TECHNOLOGIES LIMITED LIABILITY COMPANY
 * All Rights Reserved.
 */

package io.tarantool.client.crud.options;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.tarantool.client.crud.TarantoolCrudClient;
import io.tarantool.client.crud.TarantoolCrudSpace;
import io.tarantool.mapping.crud.CrudBatchResponse;

/**
 * The class implements options for the CRUD operation <a
 * href="https://github.com/tarantool/crud#insert-many">insert_many()</a>.
 *
 * <p>The following options are available:
 *
 * <p>Common options:
 *
 * <ul>
 *   <li>{@link #timeout}.
 *   <li>{@link #streamId}.
 * </ul>
 *
 * <p>Crud options:
 *
 * <ul>
 *   <li>{@value TIMEOUT}.
 *   <li>{@value FIELDS}.
 *   <li>{@value STOP_ON_ERROR}.
 *   <li>{@value ROLLBACK_ON_ERROR}.
 *   <li>{@value VSHARD_ROUTER}.
 *   <li>{@value SKIP_NULLABILITY_CHECK_ON_FLATTEN}.
 *   <li>{@value NO_RETURN}.
 *   <li>{@value FETCH_LATEST_METADATA}.
 * </ul>
 *
 * <p>Examples:
 *
 * <blockquote>
 *
 * <pre>{@code
 * <<Example 1>>
 *
 *  TarantoolCrudSpace space = crudClient.space("spaceName");
 *  long timeout = 3_000L;
 *  Map<String, Object> options = new HashMap<String, Object>(){{
 *      put("timeout", 2_000L);
 *      // Determine which fields will be returned
 *      put("fields", Arrays.asList("id", "name"));
 *  }};
 *
 *  InsertManyOptions option = new InsertManyOptions(timeout, null, options);
 *
 *  List<List<?>> tuples = Arrays.asList(Arrays.asList(1, true, "Vanya"), Arrays.asList(2, false, "Petya");
 *
 *  // Inserts tuple (id = 1, isMarried = true, name = "Vanya") and tuple (id = 2, isMarried = false, name = "Petya")
 *  // Returns BatchResponse object with two tuple as list [1, "Vanya"] and [2, "Petya"]
 *  BatchResponse<?> res = space.insertMany(tuples, option).get();
 * }</pre>
 *
 * </blockquote>
 *
 * <blockquote>
 *
 * <pre>{@code
 * <<Example 2>>
 *
 * TarantoolCrudSpace space = crudClient.space("spaceName");
 *
 * InsertManyOptions options = InsertManyOptions.builder()
 *                                                  .withTimeout(3_000L)
 *                                                  .withCrudTimeout(2_000L)
 *                                                  .withFields("id", "name")
 *                                                  .build();
 *
 *  List<List<?>> tuples = Arrays.asList(Arrays.asList(1, true, "Vanya"), Arrays.asList(2, false, "Petya");
 *
 *  // Inserts tuple (id = 1, isMarried = true, name = "Vanya") and tuple (id = 2, isMarried = false, name = "Petya")
 *  // Returns BatchResponse object with two tuple as list [1, "Vanya"] and [2, "Petya"]
 *  CrudBatchResponse<?> res = space.insertMany(tuples, options);
 * }</pre>
 *
 * </blockquote>
 *
 * @author <a href="https://github.com/ArtDu">Artyom Dubinin</a>
 * @author <a href="https://github.com/nickkkccc">Nikolay Belonogov</a>
 * @see TarantoolCrudClient
 * @see TarantoolCrudSpace
 * @see CrudBatchResponse
 */
public class InsertManyOptions implements CrudOptions {

  private static final Logger LOGGER = LoggerFactory.getLogger(InsertManyOptions.class);

  /**
   * {@link TarantoolCrudClient#call(String) vshard.call} timeout and vshard master discovery
   * timeout (in milliseconds).
   *
   * <p><i><b>Note</b></i>: The time indicated by this parameter is the time between sending a
   * message from the router to Tarantool instance and the time when the answer will come from
   * Tarantool instance to router.
   */
  private static final String TIMEOUT = "timeout";

  /** Field names for getting only a subset of fields. */
  private static final String FIELDS = "fields";

  /**
   * Stop on a first error and report error regarding the failed operation and error about what
   * tuples were not performed, default is <tt>false</tt>.
   */
  private static final String STOP_ON_ERROR = "stop_on_error";

  /**
   * Any failed operation will lead to rollback on a storage, where the operation is failed, report
   * error about what tuples were rollback, default is <tt>false</tt>.
   */
  private static final String ROLLBACK_ON_ERROR = "rollback_on_error";

  /**
   * Cartridge vshard group name. Set this parameter if your space is not a part of the default
   * vshard cluster.
   */
  private static final String VSHARD_ROUTER = "vshard_router";

  /**
   * Option for insert_object_many only. false by default. Set this parameter to true if you want to
   * allow setting null values to non-nullable fields, which can be useful if non-nullable field
   * value is generated by <a
   * href="https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_schema_sequence/create_index/">sequence</a>.
   * Warning: there is no native support for sequences in sharded systems since each replicaset has
   * its own sequence. If sequence field is a part of the sharding key (which is true by default),
   * choosing the bucket id is the sole responsibility of the developer
   */
  private static final String SKIP_NULLABILITY_CHECK_ON_FLATTEN =
      "skip_nullability_check_on_flatten";

  /**
   * Suppress successfully processed tuple (first return value is nil (null)). <tt>False</tt> by
   * default.
   */
  private static final String NO_RETURN = "noreturn";

  /**
   * Guarantees the up-to-date metadata (space format) in first return value, otherwise it may not
   * take into account the latest migration of the data format. Performance overhead is up to 15%.
   * <tt>False</tt> by default .
   */
  private static final String FETCH_LATEST_METADATA = "fetch_latest_metadata";

  /** Default value for {@link #timeout}. */
  public static final long DEFAULT_TIMEOUT = 5_000;

  /**
   * The time after which the request is considered invalid (in milliseconds).
   *
   * <p>Default value: {@value #DEFAULT_TIMEOUT} milliseconds.
   *
   * <p><i><b>Note</b></i>: The time indicated by this parameter is the time between sending a
   * message from the connector to Tarantool and the time when the answer will come from Tarantool
   * to connector.
   */
  private final Long timeout;

  /**
   * Stream id for count operation.
   *
   * <p>Default value: {@code null}.
   *
   * @see <a
   *     href="https://www.tarantool.io/ru/doc/latest/dev_guide/internals/iproto/streams/">Tarantool
   *     documentation</a>
   */
  private final Long streamId;

  /** A map containing the correspondence between option names and their meanings. */
  private final Map<String, Object> crudOptions;

  /**
   * Creates a {@link InsertManyOptions} object with the given parameters.
   *
   * @param timeout {@link #timeout}
   * @param streamId {@link #streamId}
   * @param options {@link #crudOptions}
   * @see InsertManyOptions
   */
  public InsertManyOptions(Long timeout, Long streamId, Map<String, Object> options) {
    this.crudOptions = options;

    this.timeout = timeout;
    this.streamId = streamId;
  }

  /**
   * Creates new builder instance of this class.
   *
   * @return {@link InsertManyOptions.Builder} object
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns value of timeout option.
   *
   * @return {@link #timeout} value.
   */
  @Override
  public long getTimeout() {
    return timeout;
  }

  /**
   * Returns value of stream id option.
   *
   * @return {@link #streamId} value.
   */
  @Override
  public Long getStreamId() {
    return streamId;
  }

  /**
   * Returns an immutable option map for the count operation.
   *
   * @return {@link Map} object.
   */
  @Override
  public Map<String, Object> getOptions() {
    return Collections.unmodifiableMap(crudOptions);
  }

  /**
   * Builder class for {@link InsertManyOptions}.
   *
   * @see InsertManyOptions
   */
  public static class Builder {

    /** See also: {@link InsertManyOptions#crudOptions}. */
    private final Map<String, Object> options = new HashMap<>();

    /** See also: {@link InsertManyOptions#timeout}. */
    private long timeout = DEFAULT_TIMEOUT;

    /** See also: {@link InsertManyOptions#streamId}. */
    private Long streamId;

    /**
     * Sets value of {@link #timeout} option. Timeout parameter should be greater than 0.
     *
     * @param timeout value of timeout option.
     * @return {@link InsertManyOptions.Builder} object.
     * @throws IllegalArgumentException when timeout &#8804; 0.
     * @see InsertManyOptions#timeout
     * @see InsertManyOptions
     */
    public Builder withTimeout(long timeout) {
      if (timeout <= 0) {
        throw new IllegalArgumentException("timeout should be greater than 0");
      }
      this.timeout = timeout;
      return this;
    }

    /**
     * Sets value of {@link #streamId} option. StreamId parameter should be greater or equal 0.
     *
     * @param streamId value of stream id option
     * @return {@link InsertManyOptions.Builder} object
     * @throws IllegalArgumentException when streamId &#60; 0
     * @see InsertManyOptions#streamId
     * @see InsertManyOptions
     */
    public Builder withStreamId(long streamId) {
      if (streamId < 0) {
        throw new IllegalArgumentException("streamId should be greater or equal 0");
      }
      this.streamId = streamId;
      return this;
    }

    /**
     * Sets value of {@link #TIMEOUT} option. Timeout parameter should be greater or equal 0.
     *
     * @param timeout value of {@link #TIMEOUT} option
     * @return {@link InsertManyOptions.Builder} object
     * @see #TIMEOUT
     * @see InsertManyOptions
     */
    public Builder withCrudTimeout(long timeout) {
      addOption(TIMEOUT, timeout);
      return this;
    }

    /**
     * Adds options by name into {@link #options} map. Name parameter should not be equal {@code
     * null}.
     *
     * @param name name of option
     * @param value value of option
     * @see InsertManyOptions
     * @see InsertManyOptions.Builder
     */
    private void addOption(String name, Object value) {
      if (name == null) {
        LOGGER.warn("Option isn't used since name of option is null, value = {}", value);
        return;
      }
      this.options.put(name, value);
    }

    /**
     * Sets value of {@link #FIELDS} option. Fields parameter should not be equal null.
     *
     * @param fields value of {@link #FIELDS} option
     * @return {@link InsertManyOptions.Builder} object
     * @see #FIELDS
     * @see InsertManyOptions
     */
    public Builder withFields(String... fields) {
      addOption(FIELDS, Arrays.asList(fields));
      return this;
    }

    /**
     * Sets value of {@link #FIELDS} option. Fields parameter should not be equal null.
     *
     * @param fields value of {@link #FIELDS} option
     * @return {@link InsertManyOptions.Builder} object
     * @see #FIELDS
     * @see InsertManyOptions
     */
    public Builder withFields(List<String> fields) {
      addOption(FIELDS, fields);
      return this;
    }

    /**
     * Sets value of {@link #VSHARD_ROUTER} option.
     *
     * @param vshardRouter value of {@link #VSHARD_ROUTER} option
     * @return {@link InsertManyOptions.Builder}
     * @see #VSHARD_ROUTER
     * @see InsertManyOptions
     */
    public Builder withVshardRouter(List<String> vshardRouter) {
      addOption(VSHARD_ROUTER, vshardRouter);
      return this;
    }

    /**
     * Sets value of {@link #SKIP_NULLABILITY_CHECK_ON_FLATTEN} to <tt>true</tt>.
     *
     * @return {@link InsertManyOptions.Builder} object
     * @see #SKIP_NULLABILITY_CHECK_ON_FLATTEN
     * @see InsertManyOptions
     */
    public Builder skipNullabilityCheckOnFlatten() {
      addOption(SKIP_NULLABILITY_CHECK_ON_FLATTEN, true);
      return this;
    }

    /**
     * Sets value of {@link #NO_RETURN} to <tt>true</tt>.
     *
     * @return {@link InsertManyOptions.Builder} object
     * @see #NO_RETURN
     * @see InsertManyOptions
     */
    public Builder withNoReturn() {
      addOption(NO_RETURN, true);
      return this;
    }

    /**
     * Sets value of {@link #FETCH_LATEST_METADATA} to <tt>true</tt>.
     *
     * @return {@link InsertManyOptions.Builder} object
     * @see #FETCH_LATEST_METADATA
     * @see InsertManyOptions
     */
    public Builder fetchLatestMetadata() {
      addOption(FETCH_LATEST_METADATA, true);
      return this;
    }

    /**
     * Sets value of {@link #STOP_ON_ERROR} to <tt>true</tt>.
     *
     * @return {@link InsertManyOptions.Builder} object
     * @see #STOP_ON_ERROR
     * @see InsertManyOptions
     */
    public Builder stopOnError() {
      addOption(STOP_ON_ERROR, true);
      return this;
    }

    /**
     * Sets value of {@link #ROLLBACK_ON_ERROR} to <tt>true</tt>.
     *
     * @return {@link InsertManyOptions.Builder} object
     * @see #ROLLBACK_ON_ERROR
     * @see InsertManyOptions
     */
    public Builder rollbackOnError() {
      addOption(ROLLBACK_ON_ERROR, true);
      return this;
    }

    /**
     * Sets options by name and value. OptionName parameter should not be equal {@code null}.
     *
     * @param optionName name of option
     * @param optionValue value of option
     * @return {@link InsertManyOptions.Builder}
     * @see InsertManyOptions
     */
    public Builder withOption(String optionName, Object optionValue) {
      addOption(optionName, optionValue);
      return this;
    }

    /**
     * Builds object of {@link InsertManyOptions} class.
     *
     * @return {@link InsertManyOptions} object
     * @see InsertManyOptions
     */
    public InsertManyOptions build() {
      return new InsertManyOptions(timeout, streamId, options);
    }
  }
}
