name: Bug Report
description: File a bug report.
title: ":lady_beetle: "
labels: ["bug", "triage"]
assignees: []
type: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Environment

  - type: input
    id: java-version
    attributes:
      label: Java version
      description: e.g., 17.0.10
      placeholder: 17.0.10
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: e.g., Ubuntu 24.04, MacOS, Win 11
      placeholder: Ubuntu 24.04
    validations:
      required: true

  - type: input
    id: architecture
    attributes:
      label: Architecture
      description: e.g., amd64, arm
      placeholder: amd64
    validations:
      required: true

  - type: input
    id: tjsdk-version
    attributes:
      label: Tarantool Java SDK version
      description: e.g., 1.2.3
      placeholder: 1.2.3
    validations:
      required: true

  - type: textarea
    id: other-deps
    attributes:
      label: Other relevant dependencies and versions
      description: List any other relevant dependencies and their versions.
      placeholder: |
        - testcontainers: 1.19.7
        - ...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Describe the bug

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Steps to Reproduce

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide a step-by-step guide to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Expected behavior

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Actual behavior

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened? Please include full error messages and stack traces if available.
      placeholder: Describe the actual behavior.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additional context

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, including links to related issues, logs, screenshots, or configuration files.
      placeholder: Additional context
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Minimal reproducible example (if possible)

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal reproducible example
      description: Please provide a minimal code sample or a link to a repository that demonstrates the issue.
      placeholder: |
        ```java
        // Your code here
        ```
    validations:
      required: false